### ISSUE TITLE
jargon is really hard to relate to

### ISSUE THREAD

**Issue by boxxxie** [HealthSamurai/ironhide#2]
bullet, sight, charge, magazine, shell.
please do a write up of these terms and explain them with analogy or anything so they can make sense to someone reading the docs, as to avoid confusion.

When I read through the docs I felt that these names are just randomly assigned, and are a distraction to understanding the logic of the tool.

though, to be honest, after reading the full docs I have trouble understanding the examples and how to use the tool. all I can grasp is the high level idea of bidireccional transformations. but I don't really see examples of this in the docs.

some of the docs are very confusing, eg: bullets. the example code doesn't make it clear what I'm looking at, and why any of the lines are or are not bullets.)

I don't want to be an ass. I came to this lib because some people I know recommended it. I'm very interested in the high level idea, as it would help me solve some SOAP stuff I'm working on, but after reading the docs I'm left with the feeling that I would need to spend a lot of time just playing with the lib to figure out basic usage.

**Comment by abcdw** [comment]
Hi Paul.

All these terms were a part of an experiment, wanted to see feedback how confusing/helpful such words, which not related to computer science. I received several reports similar to your and it seems that the idea was far from perfect. That is why I plan to rewrite part of readme in the next few weeks and radically reduce the number of strange terms : )

At the beginning of readme, you can find a live demo, which contains different interactive examples. 
https://healthsamurai.github.io/ironhide/

Other interesting examples can be found in tests:
https://github.com/HealthSamurai/ironhide/blob/master/test/ironhide/core_test.clj

I had a talk about ironhide on functional programming meetup and prepared slides for it, they not very useful without my speech, but may help:
https://healthsamurai.github.io/ironhide/slides/#/

Thanks a lot for such detailed feedback. Also, I will be glad to discuss your case or explain tricky parts of Ironhide. We can talk here or make a call, just drop me an email.

**Comment by boxxxie** [comment]
thanks a lot for replying.

i looked the the live demo, and at the time i couldn't understand it. to be honest it looked broken many of the transformations have nil as their value.
i think the live demo needs some more documentation as to what is going on with the transformations.

i did look at the tests. i think i need to spend some time on trying to use the lib, which may not be for a week or so (the soap project doesn't need the transformations yet, but it will eventually benefit from hiccup to obj transformation, right now i have a walk function that sorta does what i want, but isn't really maintainable).
